<?php

/**
 * @file
 * An Islandora viewer module using Video.js.
 */

/**
 * Implements hook_islandora_viewer_info().
 */
function islandora_videojs_islandora_viewer_info() {
  return [
    'islandora_videojs' => [
      'label' => t('video.js player'),
      'description' => t('video.js for audio and/or video.'),
      'callback' => 'islandora_videojs_callback',
      'mimetype' => ['audio/mpeg', 'video/mp4'],
      'configuration' => 'admin/islandora/islandora_viewers/videojs',
    ],
  ];
}

/**
 * Implements hook_theme().
 */
function islandora_videojs_theme($existing, $type, $theme, $path) {
  return [
    'islandora_videojs' => [
      'variables' => ['object' => NULL, 'params' => NULL],
    ],
  ];
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_islandora_videojs(array &$variables) {
  $params = $variables['params'];
  $variables['sources'] = [];
  if (isset($params['tn'])) {
    $variables['tn'] = $params['tn'];
  }
  $videojs_path = libraries_get_path("video-js");
  // @FIXME
// The Assets API has totally changed. CSS, JavaScript, and libraries are now
// attached directly to render arrays using the #attached property.
//
//
// @see https://www.drupal.org/node/2169605
// @see https://www.drupal.org/node/2408597
// drupal_add_js($videojs_path . "/video.js");

  // @FIXME
// The Assets API has totally changed. CSS, JavaScript, and libraries are now
// attached directly to render arrays using the #attached property.
//
//
// @see https://www.drupal.org/node/2169605
// @see https://www.drupal.org/node/2408597
// drupal_add_css($videojs_path . '/video-js.css');

  if (\Drupal::config('islandora_videojs.settings')->get('islandora_videojs_hls_library')) {
    // @FIXME
// The Assets API has totally changed. CSS, JavaScript, and libraries are now
// attached directly to render arrays using the #attached property.
//
//
// @see https://www.drupal.org/node/2169605
// @see https://www.drupal.org/node/2408597
// drupal_add_js($videojs_path . "/videojs-contrib-hls.js");

  }
  if (isset($params['sources']) && is_array($params['sources'])) {
    $variables['sources'] = $params['sources'];
  }
  elseif (isset($params['url']) && isset($params['mime'])) {
    $variables['sources'][] = ['url' => $params['url'], 'mime' => $params['mime']];
  }
  $variables['center_play_button'] = \Drupal::config('islandora_videojs.settings')->get('islandora_videojs_center_play_button');
  $variables['responsive'] = \Drupal::config('islandora_videojs.settings')->get('islandora_videojs_responsive');
  if (\Drupal::config('islandora_videojs.settings')->get('islandora_videojs_responsive')) {
    // @FIXME
// The Assets API has totally changed. CSS, JavaScript, and libraries are now
// attached directly to render arrays using the #attached property.
//
//
// @see https://www.drupal.org/node/2169605
// @see https://www.drupal.org/node/2408597
// drupal_add_css(drupal_get_path('module', 'islandora_videojs') . '/css/videojs_responsive.css', array('group' => CSS_DEFAULT, 'every_page' => FALSE));

  }
}

/**
 * Callback function to process audio player.
 *
 * @param array $params
 *   Array with configuration info for the audio player.
 */
function islandora_videojs_callback($params = []) {
  // @FIXME
// theme() has been renamed to _theme() and should NEVER be called directly.
// Calling _theme() directly can alter the expected output and potentially
// introduce security issues (see https://www.drupal.org/node/2195739). You
// should use renderable arrays instead.
//
//
// @see https://www.drupal.org/node/2195739
// return theme('islandora_videojs', array('params' => $params));

}
